  # # Push the image to Google Container Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/my-fastapi-app:$SHORT_SHA']

  # # Deploy the image to Cloud Run
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: gcloud
  #   args: ['run', 'deploy', 'my-fastapi-service',
  #          '--image', 'gcr.io/$PROJECT_ID/my-fastapi-app:$SHORT_SHA',
  #          '--region', 'us-central1',
  #          '--platform', 'managed',
  #          '--allow-unauthenticated']


  steps:
  # Step 1: Build the Docker image using Cloud Build's Docker builder
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-app:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-app:$SHORT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/fastapi-app:$SHORT_SHA'
