---
openapi: 3.1.0
info:
  title: Endepth API
  description: make API calls to models that answers questions based on natural language
  version: 0.1.0
paths:
  "/":
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  "/v1/query/":
    post:
      tags:
      - query
      summary: Query
      operationId: query_v1_query__post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/v1/query/sql_chart":
    post:
      tags:
      - query
      summary: Query Sql To Chart
      operationId: query_sql_to_chart_v1_query_sql_chart_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/v1/query/text":
    post:
      tags:
      - query
      summary: Query Combined
      operationId: query_combined_v1_query_text_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/v1/query/text_table":
    post:
      tags:
      - query
      summary: Query Table
      operationId: query_table_v1_query_text_table_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/v1/query/table_to_chart":
    post:
      tags:
      - query
      summary: Query Table To Chart
      operationId: query_table_to_chart_v1_query_table_to_chart_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/test/classify":
    post:
      tags:
      - test
      summary: Query Classify
      operationId: query_classify_test_classify_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/test/text":
    post:
      tags:
      - test
      summary: Query Text
      operationId: query_text_test_text_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/test/table_to_chart":
    post:
      tags:
      - test
      summary: Query Table To Chart
      operationId: query_table_to_chart_test_table_to_chart_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/test/sql":
    post:
      tags:
      - test
      summary: Query Sql
      operationId: query_sql_test_sql_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/test/run_sql":
    post:
      tags:
      - test
      summary: Run Sql
      operationId: run_sql_test_run_sql_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/test/sql_table":
    post:
      tags:
      - test
      summary: Query Sql To Table
      operationId: query_sql_to_table_test_sql_table_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/test/retrieval":
    post:
      tags:
      - test
      summary: Retrieval
      operationId: retrieval_test_retrieval_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QueryText"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    QueryText:
      properties:
        query:
          type: string
          title: Query
        data:
          type: string
          title: Data
      type: object
      required:
      - query
      title: QueryText
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
